/* ***** BEGIN LICENSE BLOCK *****
 *
 * Copyright (c) 2005-2007 Universidade de Sao Paulo, Sao Carlos/SP, Brazil.
 * All Rights Reserved.
 *
 * This file is part of Projection Explorer (PEx).
 *
 * How to cite this work:
 *  
@inproceedings{paulovich2007pex,
author = {Fernando V. Paulovich and Maria Cristina F. Oliveira and Rosane 
Minghim},
title = {The Projection Explorer: A Flexible Tool for Projection-based 
Multidimensional Visualization},
booktitle = {SIBGRAPI '07: Proceedings of the XX Brazilian Symposium on 
Computer Graphics and Image Processing (SIBGRAPI 2007)},
year = {2007},
isbn = {0-7695-2996-8},
pages = {27--34},
doi = {http://dx.doi.org/10.1109/SIBGRAPI.2007.39},
publisher = {IEEE Computer Society},
address = {Washington, DC, USA},
}
 *  
 * PEx is free software: you can redistribute it and/or modify it under 
 * the terms of the GNU General Public License as published by the Free 
 * Software Foundation, either version 3 of the License, or (at your option) 
 * any later version.
 *
 * PEx is distributed in the hope that it will be useful, but WITHOUT 
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License 
 * for more details.
 *
 * This code was developed by members of Computer Graphics and Image
 * Processing Group (http://www.lcad.icmc.usp.br) at Instituto de Ciencias
 * Matematicas e de Computacao - ICMC - (http://www.icmc.usp.br) of 
 * Universidade de Sao Paulo, Sao Carlos/SP, Brazil. The initial developer 
 * of the original code is Fernando Vieira Paulovich <fpaulovich@gmail.com>.
 *
 * Contributor(s): Roberto Pinho <robertopinho@yahoo.com.br>,
 *                 Rosane Minghim <rminghim@icmc.usp.br>
 *
 * You should have received a copy of the GNU General Public License along 
 * with PEx. If not, see <http://www.gnu.org/licenses/>.
 *
 * ***** END LICENSE BLOCK ***** */

package visualizer.view;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.event.HyperlinkEvent;
import javax.swing.event.HyperlinkListener;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Document;
import javax.swing.text.Highlighter;
import javax.swing.text.JTextComponent;
import visualizer.corpus.Corpus;
import visualizer.graph.Graph;
import visualizer.graph.Vertex;
import visualizer.util.SaveDialog;
import visualizer.util.filefilter.ZIPFilter;
import visualizer.view.tools.BrowserControl;

/**
 *
 * @author  Fernando Vieira Paulovich
 */
public class MultipleFileView extends javax.swing.JDialog {

    private static final long serialVersionUID = 1L;
    /**
     * Creates new form MultipleFileView
     */
    private MultipleFileView(javax.swing.JFrame parent) {
        super(parent);
        initComponents();
        this.pack();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel = new javax.swing.JPanel();
        exportButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        dataPanel = new javax.swing.JPanel();
        fileviewTabbedPane = new javax.swing.JTabbedPane();
        highlightToolBar = new javax.swing.JToolBar();
        highlightPanel = new javax.swing.JPanel();
        highlightLabel = new javax.swing.JLabel();
        highlightTextField = new javax.swing.JTextField();
        highlightButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("File Multiple View");
        setModal(true);

        exportButton.setText("Export Corpus");
        exportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(exportButton);

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(closeButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        dataPanel.setLayout(new java.awt.BorderLayout());

        fileviewTabbedPane.setMinimumSize(new java.awt.Dimension(1000, 500));
        fileviewTabbedPane.setPreferredSize(new java.awt.Dimension(800, 500));
        fileviewTabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                fileviewTabbedPaneStateChanged(evt);
            }
        });
        dataPanel.add(fileviewTabbedPane, java.awt.BorderLayout.CENTER);

        highlightPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        highlightLabel.setText("Highlight");
        highlightPanel.add(highlightLabel);

        highlightTextField.setColumns(20);
        highlightTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                highlightTextFieldKeyPressed(evt);
            }
        });
        highlightPanel.add(highlightTextField);

        highlightButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbarButtonGraphics/general/TipOfTheDay16.gif"))); // NOI18N
        highlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highlightButtonActionPerformed(evt);
            }
        });
        highlightPanel.add(highlightButton);

        highlightToolBar.add(highlightPanel);

        dataPanel.add(highlightToolBar, java.awt.BorderLayout.SOUTH);

        getContentPane().add(dataPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileviewTabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_fileviewTabbedPaneStateChanged
        if (this.fileviewTabbedPane.getSelectedComponent() instanceof FilePane) {
            this.showedFilePane = (FilePane) this.fileviewTabbedPane.getSelectedComponent();

            if (this.showedFilePane != null) {
                if (this.highlightTextField.getText().trim().length() > 0) {
                    this.showedFilePane.highlight(this.showedFilePane.textArea, this.highlightTextField.getText().trim());
                }
            }
        }
    }//GEN-LAST:event_fileviewTabbedPaneStateChanged

    private void highlightTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_highlightTextFieldKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            if (this.showedFilePane != null) {
                if (this.highlightTextField.getText().trim().length() > 0) {
                    this.showedFilePane.highlight(this.showedFilePane.textArea, this.highlightTextField.getText().trim());
                }
            }
        }
    }//GEN-LAST:event_highlightTextFieldKeyPressed

    private void highlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highlightButtonActionPerformed
        if (this.showedFilePane != null) {
            if (this.highlightTextField.getText().trim().length() > 0) {
                this.showedFilePane.highlight(this.showedFilePane.textArea, this.highlightTextField.getText().trim());
            }
        }
    }//GEN-LAST:event_highlightButtonActionPerformed

    private void exportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportButtonActionPerformed
        int result = SaveDialog.showSaveDialog(new ZIPFilter(), this);

        if (result == JFileChooser.APPROVE_OPTION) {
            String filename = SaveDialog.getFilename();
            this.graph.exportCorpus(filename, this.vertex);
            this.setVisible(false);
        }
    }//GEN-LAST:event_exportButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_closeButtonActionPerformed

    public static MultipleFileView getInstance(javax.swing.JFrame parent) {
        if (instance == null || instance.getParent() != parent) {
            instance = new MultipleFileView(parent);
        }
        return instance;
    }

    public void display(Viewer gv, ArrayList<Vertex> vertex) {
        this.vertex = vertex;
        this.graph = gv.getGraph();

        //Remove all tab pane
        this.fileviewTabbedPane.removeAll();
        this.highlightTextField.setText("");

        //Icon icon=new ImageIcon(getClass().getResource("/toolbarButtonGraphics/media/S16.gif"));

        if (vertex != null) {
            for (Vertex v : vertex) {
                if (v.isValid()) {
                    String label = v.toString();
                    if (label.length() > this.numberCharsAtTabTitle) {
                        label = label.substring(0, this.numberCharsAtTabTitle - 3) + "...";
                    }
                    this.fileviewTabbedPane.addTab(label,
                            new FilePane(v.toString(), graph.getCorpus(), v.getUrl()));
                }
            }
        }

        this.pack();
        this.setLocationRelativeTo(this.getParent());
        this.setVisible(true);
    }

    public void display(Viewer gv, Vertex vertex) {
        ArrayList<Vertex> neighbors = new ArrayList<Vertex>();
        gv.getGraph().getNeighbors(neighbors, null, gv.getCurrentConnectivity(),
                vertex, gv.getNeighborhoodDepth());
        
        if (neighbors.size() > 0) {
            neighbors.set(0, vertex);
        } else {
            neighbors.add(vertex);
        }
        
        this.display(gv, neighbors);
    }

    class FilePane extends javax.swing.JPanel {

        private static final long serialVersionUID = 1L;
        public FilePane(String label, Corpus datasource, String filename) {
            this.initComponents(label, datasource, filename);
        }

        private void initComponents(String label, Corpus datasource, String filename) {
            this.textAreaScrollPane = new javax.swing.JScrollPane();
            this.textArea = new javax.swing.JEditorPane();
            this.filelabelPanel = new javax.swing.JPanel();
            this.filelabelField = new javax.swing.JTextField();

            this.setLayout(new java.awt.BorderLayout());
            this.textAreaScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("File Content"));
            this.textAreaScrollPane.setAutoscrolls(true);
            this.textArea.setEditable(false);
            this.textArea.setAutoscrolls(false);
            this.textAreaScrollPane.setViewportView(textArea);
            this.add(textAreaScrollPane, java.awt.BorderLayout.CENTER);

            if (filename.endsWith(".html") || filename.endsWith(".htm")) {
                this.textArea.setContentType("text/html");
            }

            this.textArea.addHyperlinkListener(new HyperlinkListener() {

                @Override
                public void hyperlinkUpdate(HyperlinkEvent e) {
                    if (e.getEventType() == HyperlinkEvent.EventType.ACTIVATED) {
                        BrowserControl.displayURL(e.getURL().toString());
                    }
                }

            });

            this.filelabelPanel.setLayout(new java.awt.BorderLayout());
            this.filelabelPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("File Label"));
            this.filelabelField.setEditable(false);
            this.filelabelPanel.add(filelabelField, java.awt.BorderLayout.CENTER);
            this.add(filelabelPanel, java.awt.BorderLayout.NORTH);

            //Loading the data
            this.filelabelField.setText(label);
            this.filelabelField.setCaretPosition(0);

            try {
                this.textArea.setText(datasource.getViewContent(filename));
                this.textArea.setCaretPosition(0);
            } catch (IOException ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
            }
        }

        // Creates highlights around all occurrences of pattern in textComp
        public void highlight(JTextComponent textComp, String pattern) {
            // First remove all old highlights
            removeHighlights(textComp);

            try {
                Highlighter hilite = textComp.getHighlighter();
                Document doc = textComp.getDocument();
                String text = doc.getText(0, doc.getLength()).toLowerCase();
                int pos = 0;

                if ((pos = text.indexOf(pattern.toLowerCase(), pos)) >= 0) {
                    // Create highlighter using private painter and apply around pattern
                    hilite.addHighlight(pos, pos + pattern.length(), myHighlightPainter);
                    this.textArea.setCaretPosition(pos);
                    pos += pattern.length();
                }

                // find for pattern
                while ((pos = text.indexOf(pattern.toLowerCase(), pos)) >= 0) {
                    // Create highlighter using private painter and apply around pattern
                    hilite.addHighlight(pos, pos + pattern.length(), myHighlightPainter);
                    pos += pattern.length();
                }
            } catch (BadLocationException e) {
            }
        }

        // Removes only our private highlights
        public void removeHighlights(JTextComponent textComp) {
            Highlighter hilite = textComp.getHighlighter();
            Highlighter.Highlight[] hilites = hilite.getHighlights();

            for (int i = 0; i < hilites.length; i++) {
                if (hilites[i].getPainter() instanceof MyHighlightPainter) {
                    hilite.removeHighlight(hilites[i]);
                }
            }
        }

        // A private subclass of the default highlight painter
        class MyHighlightPainter extends DefaultHighlighter.DefaultHighlightPainter {

            public MyHighlightPainter(java.awt.Color color) {
                super(color);
            }

        }

        private javax.swing.JTextField filelabelField;
        private javax.swing.JPanel filelabelPanel;
        private javax.swing.JEditorPane textArea;
        private javax.swing.JScrollPane textAreaScrollPane;
        // An instance of the private subclass of the default highlight painter
        private Highlighter.HighlightPainter myHighlightPainter = new MyHighlightPainter(java.awt.Color.YELLOW);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new MultipleFileView(null).setVisible(true);
            }

        });
    }

    private FilePane showedFilePane = null;
    private final int numberCharsAtTabTitle = 20;
    private static MultipleFileView instance;
    private ArrayList<Vertex> vertex;
    //private javax.swing.JFileChooser file = new javax.swing.JFileChooser();
    private Graph graph;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton closeButton;
    private javax.swing.JPanel dataPanel;
    private javax.swing.JButton exportButton;
    private javax.swing.JTabbedPane fileviewTabbedPane;
    private javax.swing.JButton highlightButton;
    private javax.swing.JLabel highlightLabel;
    private javax.swing.JPanel highlightPanel;
    private javax.swing.JTextField highlightTextField;
    private javax.swing.JToolBar highlightToolBar;
    // End of variables declaration//GEN-END:variables
}