/* ***** BEGIN LICENSE BLOCK *****
 *
 * Copyright (c) 2005-2007 Universidade de Sao Paulo, Sao Carlos/SP, Brazil.
 * All Rights Reserved.
 *
 * This file is part of Projection Explorer (PEx).
 *
 * How to cite this work:
 *  
@inproceedings{paulovich2007pex,
author = {Fernando V. Paulovich and Maria Cristina F. Oliveira and Rosane 
Minghim},
title = {The Projection Explorer: A Flexible Tool for Projection-based 
Multidimensional Visualization},
booktitle = {SIBGRAPI '07: Proceedings of the XX Brazilian Symposium on 
Computer Graphics and Image Processing (SIBGRAPI 2007)},
year = {2007},
isbn = {0-7695-2996-8},
pages = {27--34},
doi = {http://dx.doi.org/10.1109/SIBGRAPI.2007.39},
publisher = {IEEE Computer Society},
address = {Washington, DC, USA},
}
 *  
 * PEx is free software: you can redistribute it and/or modify it under 
 * the terms of the GNU General Public License as published by the Free 
 * Software Foundation, either version 3 of the License, or (at your option) 
 * any later version.
 *
 * PEx is distributed in the hope that it will be useful, but WITHOUT 
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License 
 * for more details.
 *
 * This code was developed by members of Computer Graphics and Image
 * Processing Group (http://www.lcad.icmc.usp.br) at Instituto de Ciencias
 * Matematicas e de Computacao - ICMC - (http://www.icmc.usp.br) of 
 * Universidade de Sao Paulo, Sao Carlos/SP, Brazil. The initial developer 
 * of the original code is Fernando Vieira Paulovich <fpaulovich@gmail.com>.
 *
 * Contributor(s): Rosane Minghim <rminghim@icmc.usp.br>
 *
 * You should have received a copy of the GNU General Public License along 
 * with PEx. If not, see <http://www.gnu.org/licenses/>.
 *
 * ***** END LICENSE BLOCK ***** */

package visualizer.view.tools;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import visualizer.graph.Graph;
import visualizer.graph.Connectivity;
import visualizer.projection.distance.DistanceMatrix;
import visualizer.util.KNN;
import visualizer.util.Pair;
import visualizer.util.OpenDialog;
import visualizer.util.filefilter.DMATFilter;

/**
 *
 * @author Fernando Vieira Paulovich
 */
public class KnnConnectivity extends javax.swing.JDialog {

    /** Creates new form KnnConnectivity */
    private KnnConnectivity(javax.swing.JFrame parent) {
        super(parent);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTextField1 = new javax.swing.JTextField();
        dataPanel = new javax.swing.JPanel();
        distanceMatrixTextField = new javax.swing.JTextField();
        distanceMatrixButton = new javax.swing.JButton();
        distanceMatrixLabel = new javax.swing.JLabel();
        knnConnectivityLabel = new javax.swing.JLabel();
        knnConnectivityComboBox = new javax.swing.JComboBox();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        nameComboBox = new javax.swing.JComboBox();
        inuseLabel = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create KNN Connectivity");
        setModal(true);

        dataPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("KNN Connectivity Parameters"));
        dataPanel.setLayout(new java.awt.GridBagLayout());

        distanceMatrixTextField.setColumns(35);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        dataPanel.add(distanceMatrixTextField, gridBagConstraints);

        distanceMatrixButton.setText("Search...");
        distanceMatrixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distanceMatrixButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        dataPanel.add(distanceMatrixButton, gridBagConstraints);

        distanceMatrixLabel.setText("Distance Matrix");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        dataPanel.add(distanceMatrixLabel, gridBagConstraints);

        knnConnectivityLabel.setText("Number Neighbors");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        dataPanel.add(knnConnectivityLabel, gridBagConstraints);

        knnConnectivityComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        knnConnectivityComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                knnConnectivityComboBoxItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        dataPanel.add(knnConnectivityComboBox, gridBagConstraints);

        nameLabel.setText("Connectivity Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 3, 3, 3);
        dataPanel.add(nameLabel, gridBagConstraints);

        nameTextField.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 3, 3, 3);
        dataPanel.add(nameTextField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 3, 3, 3);
        dataPanel.add(nameComboBox, gridBagConstraints);

        inuseLabel.setText("In use");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 3, 3, 3);
        dataPanel.add(inuseLabel, gridBagConstraints);

        getContentPane().add(dataPanel, java.awt.BorderLayout.CENTER);

        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        okButton.setText("Create");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(okButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(cancelButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void knnConnectivityComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_knnConnectivityComboBoxItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            String conname = "KNN-RN-" + (this.knnConnectivityComboBox.getSelectedIndex() + 1);
            this.nameTextField.setText(conname);
        }
}//GEN-LAST:event_knnConnectivityComboBoxItemStateChanged

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        if (this.distanceMatrixTextField.getText().trim().length() > 0) {
            try {
                DistanceMatrix dmat = new DistanceMatrix(this.distanceMatrixTextField.getText());

                int numberNeighbors = this.knnConnectivityComboBox.getSelectedIndex() + 1;
                String conname = this.nameTextField.getText();
                this.connectivity = new Connectivity(conname);
                KNN knn = new KNN(numberNeighbors);
                Pair[][] neighborhood = knn.execute(dmat);
                this.connectivity.create(this.graph.getVertex(), neighborhood);
                this.graph.addConnectivity(this.connectivity);
            } catch (IOException ex) {
                Logger.getLogger(KnnConnectivity.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            this.setVisible(false);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "The DISTANCE MATRIX file must be provided!",
                    "WARNING", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void distanceMatrixButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distanceMatrixButtonActionPerformed
        int result = OpenDialog.showOpenDialog(new DMATFilter(), this);

        if (result == JFileChooser.APPROVE_OPTION) {
            String filename = OpenDialog.getFilename();
            this.distanceMatrixTextField.setText(filename);
        }
    }//GEN-LAST:event_distanceMatrixButtonActionPerformed

    public static KnnConnectivity getInstance(javax.swing.JFrame parent) {
        if (instance == null || instance.getParent() != parent) {
            instance = new KnnConnectivity(parent);
        }
        return instance;
    }

    public Connectivity display(Graph graph) {
        this.graph = graph;
        this.connectivity = null;
        this.distanceMatrixTextField.setText("");
        this.knnConnectivityComboBox.setSelectedIndex(0);

        this.nameComboBox.removeAllItems();
        for (Connectivity con : this.graph.getConnectivities()) {
            this.nameComboBox.addItem(con.getName());
        }

        String conname = "KNN-RN-" + (this.knnConnectivityComboBox.getSelectedIndex() + 1);
        this.nameTextField.setText(conname);

        this.pack();
        this.setLocationRelativeTo(this.getParent());
        this.setVisible(true);

        return this.connectivity;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new KnnConnectivity(null).setVisible(true);
            }

        });
    }
    //private JFileChooser file = new JFileChooser();
    private static KnnConnectivity instance;
    private Connectivity connectivity;
    private Graph graph;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel dataPanel;
    private javax.swing.JButton distanceMatrixButton;
    private javax.swing.JLabel distanceMatrixLabel;
    private javax.swing.JTextField distanceMatrixTextField;
    private javax.swing.JLabel inuseLabel;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox knnConnectivityComboBox;
    private javax.swing.JLabel knnConnectivityLabel;
    private javax.swing.JComboBox nameComboBox;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
