/* ***** BEGIN LICENSE BLOCK *****
 *
 * Copyright (c) 2005-2007 Universidade de Sao Paulo, Sao Carlos/SP, Brazil.
 * All Rights Reserved.
 *
 * This file is part of Projection Explorer (PEx).
 *
 * How to cite this work:
 *  
@inproceedings{paulovich2007pex,
author = {Fernando V. Paulovich and Maria Cristina F. Oliveira and Rosane 
Minghim},
title = {The Projection Explorer: A Flexible Tool for Projection-based 
Multidimensional Visualization},
booktitle = {SIBGRAPI '07: Proceedings of the XX Brazilian Symposium on 
Computer Graphics and Image Processing (SIBGRAPI 2007)},
year = {2007},
isbn = {0-7695-2996-8},
pages = {27--34},
doi = {http://dx.doi.org/10.1109/SIBGRAPI.2007.39},
publisher = {IEEE Computer Society},
address = {Washington, DC, USA},
}
 * 
 * PEx is free software: you can redistribute it and/or modify it under 
 * the terms of the GNU General Public License as published by the Free 
 * Software Foundation, either version 3 of the License, or (at your option) 
 * any later version.
 *
 * PEx is distributed in the hope that it will be useful, but WITHOUT 
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License 
 * for more details.
 *
 * This code was developed by members of Computer Graphics and Image
 * Processing Group (http://www.lcad.icmc.usp.br) at Instituto de Ciencias
 * Matematicas e de Computacao - ICMC - (http://www.icmc.usp.br) of 
 * Universidade de Sao Paulo, Sao Carlos/SP, Brazil. The initial developer 
 * of the original code is Fernando Vieira Paulovich <fpaulovich@gmail.com>, 
 * Roberto Pinho <robertopinho@yahoo.com.br>.
 *
 * Contributor(s): Rosane Minghim <rminghim@icmc.usp.br>
 *
 * You should have received a copy of the GNU General Public License along 
 * with PEx. If not, see <http://www.gnu.org/licenses/>.
 *
 * ***** END LICENSE BLOCK ***** */

package visualizer.google;

import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.DefaultListModel;
import visualizer.wizard.DataSourceChoice;

/**
 *
 * @author  Fernando Vieira Paulovich
 */
public class GoogleView extends javax.swing.JDialog {

    private static final long serialVersionUID = 1L;
    /** Creates new form GoogleView */
    private GoogleView(javax.swing.JFrame parent) {
        super(parent);
        initComponents();
    }

    private GoogleView(javax.swing.JDialog parent) {
        super(parent);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        dataPanel = new javax.swing.JPanel();
        queriesExecutionPanel = new javax.swing.JPanel();
        queriesScrollPane = new javax.swing.JScrollPane();
        queriesTable = new javax.swing.JTable(this.tableModel);
        queriesButtonPanel = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        newSearchPanel = new javax.swing.JPanel();
        queryLabel = new javax.swing.JLabel();
        queryTextField = new javax.swing.JTextField();
        numberDocsSlider = new javax.swing.JSlider();
        numberDocsLabel = new javax.swing.JLabel();
        executeButton = new javax.swing.JButton();
        numberDocsTextField = new javax.swing.JTextField();
        removeCorpusPanel = new javax.swing.JPanel();
        removeCorpusScrollPane = new javax.swing.JScrollPane();
        removeCorporaList = new javax.swing.JList(this.listModel);
        removeCorpusButtonPanel = new javax.swing.JPanel();
        removeCorporaButton = new javax.swing.JButton();
        buttonPanel = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Google");
        setModal(true);
        setResizable(false);

        dataPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Google Parameters"));
        dataPanel.setMaximumSize(new java.awt.Dimension(100, 100));
        dataPanel.setMinimumSize(new java.awt.Dimension(100, 100));
        dataPanel.setLayout(new java.awt.BorderLayout());

        queriesExecutionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Queries Under Execution"));
        queriesExecutionPanel.setLayout(new java.awt.BorderLayout());

        queriesScrollPane.setMaximumSize(new java.awt.Dimension(100, 100));
        queriesScrollPane.setPreferredSize(new java.awt.Dimension(100, 100));

        queriesTable.setModel(this.tableModel);
        queriesScrollPane.setViewportView(queriesTable);

        queriesExecutionPanel.add(queriesScrollPane, java.awt.BorderLayout.CENTER);

        queriesButtonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        queriesButtonPanel.add(cancelButton);

        queriesExecutionPanel.add(queriesButtonPanel, java.awt.BorderLayout.SOUTH);

        dataPanel.add(queriesExecutionPanel, java.awt.BorderLayout.CENTER);

        newSearchPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("New Search"));
        newSearchPanel.setLayout(new java.awt.GridBagLayout());

        queryLabel.setText("Query");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        newSearchPanel.add(queryLabel, gridBagConstraints);

        queryTextField.setColumns(40);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        newSearchPanel.add(queryTextField, gridBagConstraints);

        numberDocsSlider.setMajorTickSpacing(100);
        numberDocsSlider.setMaximum(1000);
        numberDocsSlider.setMinimum(10);
        numberDocsSlider.setMinorTickSpacing(10);
        numberDocsSlider.setPaintLabels(true);
        numberDocsSlider.setPaintTicks(true);
        numberDocsSlider.setSnapToTicks(true);
        numberDocsSlider.setValue(100);
        numberDocsSlider.setPreferredSize(new java.awt.Dimension(350, 50));
        numberDocsSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                numberDocsSliderStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        newSearchPanel.add(numberDocsSlider, gridBagConstraints);

        numberDocsLabel.setText("Number Documents");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        newSearchPanel.add(numberDocsLabel, gridBagConstraints);

        executeButton.setText("Execute");
        executeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(14, 0, 5, 0);
        newSearchPanel.add(executeButton, gridBagConstraints);

        numberDocsTextField.setColumns(5);
        numberDocsTextField.setEditable(false);
        numberDocsTextField.setText("100");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        newSearchPanel.add(numberDocsTextField, gridBagConstraints);

        dataPanel.add(newSearchPanel, java.awt.BorderLayout.NORTH);

        removeCorpusPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Delete Corpus"));
        removeCorpusPanel.setLayout(new java.awt.BorderLayout());

        removeCorporaList.setVisibleRowCount(5);
        removeCorpusScrollPane.setViewportView(removeCorporaList);

        removeCorpusPanel.add(removeCorpusScrollPane, java.awt.BorderLayout.CENTER);

        removeCorpusButtonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        removeCorporaButton.setText("Remove");
        removeCorporaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeCorporaButtonActionPerformed(evt);
            }
        });
        removeCorpusButtonPanel.add(removeCorporaButton);

        removeCorpusPanel.add(removeCorpusButtonPanel, java.awt.BorderLayout.SOUTH);

        dataPanel.add(removeCorpusPanel, java.awt.BorderLayout.SOUTH);

        getContentPane().add(dataPanel, java.awt.BorderLayout.CENTER);

        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(closeButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void removeCorporaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCorporaButtonActionPerformed
        Object[] queries = this.removeCorporaList.getSelectedValues();
        GoogleSearchManager manager = GoogleSearchManager.getInstance();

        if (queries.length > 0) {
            for (int i = 0; i < queries.length; i++) {
                String file = manager.getCorpus((String) queries[i]);
                manager.removeQuery((String) queries[i]);
                this.listModel.removeElement(queries[i]);

                File f = new File(file);
                if (f.exists()) {
                    f.delete();
                }
                System.out.println(file);
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "It is necessary to select a query to remove!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }

        if (this.dataSourceChoice != null) {
            dataSourceChoice.reset();
        }
    }//GEN-LAST:event_removeCorporaButtonActionPerformed

    private void numberDocsSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_numberDocsSliderStateChanged
        this.numberDocsTextField.setText(Integer.toString(this.numberDocsSlider.getValue()));
    }//GEN-LAST:event_numberDocsSliderStateChanged

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        if (this.queriesTable.getSelectedRow() >= 0) {
            GoogleSearch gsearch = this.searches.get(this.queriesTable.getSelectedRow());
            gsearch.stopSearch();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "It is necessary to select a query to cancel!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void executeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeButtonActionPerformed
        if (this.queryTextField.getText().trim().length() > 0) {
            GoogleSearch gsearch = new GoogleSearch("8wE642dQFHKK9JfZqVTeQdBnbKJQrSpG", this);
            gsearch.search(this.queryTextField.getText(), this.numberDocsSlider.getValue());
            this.searches.add(gsearch);
            this.tableModel.addRow(gsearch);
            this.queryTextField.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "It is necessary to provide a query!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_executeButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_closeButtonActionPerformed

    public static GoogleView getInstance(java.awt.Container parent) {
        if (instance == null || instance.getParent() != parent) {
            if (parent instanceof javax.swing.JFrame) {
                instance = new GoogleView((javax.swing.JFrame) parent);
            } else {
                instance = new GoogleView((javax.swing.JDialog) parent);
            }
        }
        return instance;
    }

    public void display(DataSourceChoice dataSourceChoice) {
        this.dataSourceChoice = dataSourceChoice;
        this.queryTextField.setText("");
        this.numberDocsSlider.setValue(0);

        GoogleSearchManager manager = GoogleSearchManager.getInstance();
        String[] queries = manager.getQueries();
        Arrays.sort(queries);

        this.listModel.clear();
        for (String query : queries) {
            this.listModel.addElement(query);
        }

        this.pack();
        this.setLocationRelativeTo(this.getParent());
        this.setVisible(true);
    }

    public void updateTable() {
        this.tableModel.update();
    }

    public synchronized void removeQuery(GoogleSearch gsearch) {
        int index = this.searches.indexOf(gsearch);
        if (index > -1) {
            this.searches.remove(index);
            this.tableModel.removeRow(index);
        }
    }

    public synchronized void queryFinished(GoogleSearch gsearch) {
        if (!this.isVisible()) {
            //quando terminar a busca avisa o usuário
            String msg = "Query towards " + gsearch.getQuery().substring(0, gsearch.getQuery().lastIndexOf("[")) + " is finished!";
            javax.swing.JOptionPane.showMessageDialog(this, msg, "Query finished", javax.swing.JOptionPane.WARNING_MESSAGE);
        }

        this.removeQuery(gsearch);
        this.listModel.addElement(gsearch.getQuery());

        if (this.dataSourceChoice != null) {
            dataSourceChoice.reset();
        }
    }

    private DefaultListModel listModel = new DefaultListModel();
    private GoogleSearchTableModel tableModel = new GoogleSearchTableModel();
    private ArrayList<GoogleSearch> searches = new ArrayList<GoogleSearch>();
    private DataSourceChoice dataSourceChoice;
    private static GoogleView instance;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new GoogleView(new javax.swing.JFrame()).setVisible(true);
            }

        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JPanel dataPanel;
    private javax.swing.JButton executeButton;
    private javax.swing.JPanel newSearchPanel;
    private javax.swing.JLabel numberDocsLabel;
    private javax.swing.JSlider numberDocsSlider;
    private javax.swing.JTextField numberDocsTextField;
    private javax.swing.JPanel queriesButtonPanel;
    private javax.swing.JPanel queriesExecutionPanel;
    private javax.swing.JScrollPane queriesScrollPane;
    private javax.swing.JTable queriesTable;
    private javax.swing.JLabel queryLabel;
    private javax.swing.JTextField queryTextField;
    private javax.swing.JButton removeCorporaButton;
    private javax.swing.JList removeCorporaList;
    private javax.swing.JPanel removeCorpusButtonPanel;
    private javax.swing.JPanel removeCorpusPanel;
    private javax.swing.JScrollPane removeCorpusScrollPane;
    // End of variables declaration//GEN-END:variables
}
