/* ***** BEGIN LICENSE BLOCK *****
 *
 * Copyright (c) 2005-2007 Universidade de Sao Paulo, Sao Carlos/SP, Brazil.
 * All Rights Reserved.
 *
 * This file is part of Projection Explorer (PEx).
 *
 * How to cite this work:
 *  
@inproceedings{paulovich2007pex,
author = {Fernando V. Paulovich and Maria Cristina F. Oliveira and Rosane 
Minghim},
title = {The Projection Explorer: A Flexible Tool for Projection-based 
Multidimensional Visualization},
booktitle = {SIBGRAPI '07: Proceedings of the XX Brazilian Symposium on 
Computer Graphics and Image Processing (SIBGRAPI 2007)},
year = {2007},
isbn = {0-7695-2996-8},
pages = {27--34},
doi = {http://dx.doi.org/10.1109/SIBGRAPI.2007.39},
publisher = {IEEE Computer Society},
address = {Washington, DC, USA},
}
 *  
 * PEx is free software: you can redistribute it and/or modify it under 
 * the terms of the GNU General Public License as published by the Free 
 * Software Foundation, either version 3 of the License, or (at your option) 
 * any later version.
 *
 * PEx is distributed in the hope that it will be useful, but WITHOUT 
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License 
 * for more details.
 *
 * This code was developed by members of Computer Graphics and Image
 * Processing Group (http://www.lcad.icmc.usp.br) at Instituto de Ciencias
 * Matematicas e de Computacao - ICMC - (http://www.icmc.usp.br) of 
 * Universidade de Sao Paulo, Sao Carlos/SP, Brazil. The initial developer 
 * of the original code is Fernando Vieira Paulovich <fpaulovich@gmail.com>.
 *
 * Contributor(s): Roberto Pinho <robertopinho@yahoo.com.br>, 
 *                 Rosane Minghim <rminghim@icmc.usp.br>
 *
 * You should have received a copy of the GNU General Public License along 
 * with PEx. If not, see <http://www.gnu.org/licenses/>.
 *
 * ***** END LICENSE BLOCK ***** */

package visualizer.view;

import visualizer.util.SystemPropertiesManager;

/**
 *
 * @author  Fernando Vieira Paulovich
 */
public class Help extends javax.swing.JDialog {

    /** Creates new form Help */
    private Help(javax.swing.JFrame parent) {
        super(parent);
        initComponents();
        createMessage();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        helpTabbedPane = new javax.swing.JTabbedPane();
        detailPanel = new javax.swing.JPanel();
        detailsScrollPane = new javax.swing.JScrollPane();
        detailsEditorPane = new javax.swing.JEditorPane();
        aboutPanel = new Splash.SplashPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About");
        setModal(true);
        setResizable(false);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(okButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        detailPanel.setLayout(new java.awt.BorderLayout());

        detailsEditorPane.setContentType("text/html");
        detailsEditorPane.setEditable(false);
        detailsScrollPane.setViewportView(detailsEditorPane);

        detailPanel.add(detailsScrollPane, java.awt.BorderLayout.CENTER);

        helpTabbedPane.addTab("Details", detailPanel);
        helpTabbedPane.addTab("About", aboutPanel);

        getContentPane().add(helpTabbedPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_okButtonActionPerformed

    public static Help getInstance(javax.swing.JFrame parent) {
        if (instance == null || instance.getParent() != parent) {
            instance = new Help(parent);
        }
        return instance;
    }

    public void display() {
        this.pack();
        this.setLocationRelativeTo(this.getParent());
        this.setVisible(true);
    }

    private void createMessage() {
        String version = SystemPropertiesManager.getInstance().getProperty("TOOL.VERSION");
        if (version == null || version.trim().length() < 1) {
            version = "**.**.**";
        }

        String message = "<p style=\"word-spacing: 0; margin: 0\"><b><font size=\"5\" color=\"#0000FF\" face=\"Verdana\">Projection Explorer for Images (version " + version + ")</font></b></p>" +
                "<p style=\"word-spacing: 0; margin: 0\"><b><font face=\"Verdana\" size=\"4\">University of São Paulo (USP) - São Carlos/SP, Brazil</font></b></p>" +
                "<p style=\"word-spacing: 0; margin: 0\"><b><font face=\"Verdana\" size=\"3\">Matemathical and Computer Science Institute (ICMC)</font></b></p>" +
                "<p style=\"word-spacing: 0; margin: 0\"><font face=\"Verdana\" size=\"3\">Computer Graphics and Image Processing Group</font></p>" +
                "<p style=\"word-spacing: 0; margin: 0\">&nbsp;</p>" +
                "<p style=\"word-spacing: 0; margin: 0\"><font face=\"Verdana\" size=\"3\" color=\"#0000FF\">http://infoserver.lcad.icmc.usp.br/infovis2/PExImage</font></p>" +
                "<p style=\"word-spacing: 0; margin: 0\">&nbsp;</p>" +
                "<p style=\"word-spacing: 0; margin: 0\"><font face=\"Verdana\" size=\"3\"><b>Supervisor:</b></font></p>" +
                "<p style=\"word-spacing: 0; margin: 0\"><font face=\"Verdana\" size=\"3\">&nbsp;&nbsp;&nbsp;&nbsp;Rosane Minghim (rminghim@icmc.usp.br)</font></p>" +
                "<p style=\"word-spacing: 0; margin: 0\">&nbsp;</p>" +
                "<p style=\"word-spacing: 0; margin: 0\"><font face=\"Verdana\" size=\"3\"><b>Developers:</b></font></p>" +
                "<p style=\"word-spacing: 0; margin: 0\"><font face=\"Verdana\" size=\"3\">&nbsp;&nbsp;&nbsp;&nbsp;Danilo Medeiros Eler (danilome@gmail.com)</font></p>" +                
                "<p style=\"word-spacing: 0; margin: 0\"><font face=\"Verdana\" size=\"3\">&nbsp;&nbsp;&nbsp;&nbsp;Fernando Vieira Paulovich (fpaulovich@gmail.com)</font></p>" +
                "<p style=\"word-spacing: 0; margin: 0\"><font face=\"Verdana\" size=\"3\">&nbsp;&nbsp;&nbsp;&nbsp;Gabriel de Faria Andery (gfandery@gmail.com)</font></p>" +                
                "<p style=\"word-spacing: 0; margin: 0\"><font face=\"Verdana\" size=\"3\">&nbsp;&nbsp;&nbsp;&nbsp;Marcel Yugo Nakazaki (myn@icmc.usp.br)</font></p>" +                
                "<p style=\"word-spacing: 0; margin: 0\">&nbsp;</p>" +
                "<p style=\"word-spacing: 0; margin: 0\"><font face=\"Verdana\" size=\"3\"><b>Contributors:</b></font></p>" +
                "<p style=\"word-spacing: 0; margin: 0\"><font face=\"Verdana\" size=\"3\">&nbsp;&nbsp;&nbsp;&nbsp;Davi Pereira Santos</font></p>" +
                "<p style=\"word-spacing: 0; margin: 0\"><font face=\"Verdana\" size=\"3\">&nbsp;&nbsp;&nbsp;&nbsp;João Batista do Espírito Santo Neto (jbatista@icmc.usp.br)</font></p>" +
                "<p style=\"word-spacing: 0; margin: 0\"><font face=\"Verdana\" size=\"3\">&nbsp;&nbsp;&nbsp;&nbsp;Maria Cristina Ferreira de Oliveira (cristina@icmc.usp.br)</font></p>";

        this.detailsEditorPane.setText(message);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                Help h = new Help(null);
                h.setVisible(true);
            }

        });
    }

    private static Help instance;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aboutPanel;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel detailPanel;
    private javax.swing.JEditorPane detailsEditorPane;
    private javax.swing.JScrollPane detailsScrollPane;
    private javax.swing.JTabbedPane helpTabbedPane;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
