/* ***** BEGIN LICENSE BLOCK *****
 *
 * Copyright (c) 2005-2007 Universidade de Sao Paulo, Sao Carlos/SP, Brazil.
 * All Rights Reserved.
 *
 * This file is part of Projection Explorer (PEx).
 *
 * How to cite this work:
 *  
@inproceedings{paulovich2007pex,
author = {Fernando V. Paulovich and Maria Cristina F. Oliveira and Rosane 
Minghim},
title = {The Projection Explorer: A Flexible Tool for Projection-based 
Multidimensional Visualization},
booktitle = {SIBGRAPI '07: Proceedings of the XX Brazilian Symposium on 
Computer Graphics and Image Processing (SIBGRAPI 2007)},
year = {2007},
isbn = {0-7695-2996-8},
pages = {27--34},
doi = {http://dx.doi.org/10.1109/SIBGRAPI.2007.39},
publisher = {IEEE Computer Society},
address = {Washington, DC, USA},
}
 *  
 * PEx is free software: you can redistribute it and/or modify it under 
 * the terms of the GNU General Public License as published by the Free 
 * Software Foundation, either version 3 of the License, or (at your option) 
 * any later version.
 *
 * PEx is distributed in the hope that it will be useful, but WITHOUT 
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License 
 * for more details.
 *
 * This code was developed by members of Computer Graphics and Image
 * Processing Group (http://www.lcad.icmc.usp.br) at Instituto de Ciencias
 * Matematicas e de Computacao - ICMC - (http://www.icmc.usp.br) of 
 * Universidade de Sao Paulo, Sao Carlos/SP, Brazil. The initial developer 
 * of the original code is Fernando Vieira Paulovich <fpaulovich@gmail.com>.
 *
 * Contributor(s): Rosane Minghim <rminghim@icmc.usp.br>
 *
 * You should have received a copy of the GNU General Public License along 
 * with PEx. If not, see <http://www.gnu.org/licenses/>.
 *
 * ***** END LICENSE BLOCK ***** */

/*
 * MemoryCheck.java
 *
 * Created on 29 de Maio de 2007, 11:07
 */
package visualizer.view.tools;

import java.text.NumberFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author  Fernando Vieira Paulovich
 */
public class MemoryCheck extends javax.swing.JDialog {

    /** Creates new form MemoryCheck */
    private MemoryCheck(java.awt.Frame parent) {
        super(parent);
        initComponents();

        MemoryCheck.autoCall = false;
        MemoryCheck.checker = new Checker();
        MemoryCheck.checker.start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        memoryPanel = new javax.swing.JPanel();
        currentLabel = new javax.swing.JLabel();
        currentTextField = new javax.swing.JTextField();
        maximumLabel = new javax.swing.JLabel();
        maximumTextField = new javax.swing.JTextField();
        buttonPanel = new javax.swing.JPanel();
        gcButton = new javax.swing.JButton();
        autoCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Memory Check");
        setAlwaysOnTop(true);
        setResizable(false);
        memoryPanel.setLayout(new java.awt.GridBagLayout());

        memoryPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Memory Used"));
        currentLabel.setText("Current");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        memoryPanel.add(currentLabel, gridBagConstraints);

        currentTextField.setColumns(10);
        currentTextField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        memoryPanel.add(currentTextField, gridBagConstraints);

        maximumLabel.setText("Maximum");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        memoryPanel.add(maximumLabel, gridBagConstraints);

        maximumTextField.setColumns(10);
        maximumTextField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        memoryPanel.add(maximumTextField, gridBagConstraints);

        getContentPane().add(memoryPanel, java.awt.BorderLayout.CENTER);

        buttonPanel.setLayout(new java.awt.GridBagLayout());

        gcButton.setText("Call Garbage Collector");
        gcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gcButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        buttonPanel.add(gcButton, gridBagConstraints);

        autoCheckBox.setText("Automatically");
        autoCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        autoCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));
        autoCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoCheckBoxActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        buttonPanel.add(autoCheckBox, gridBagConstraints);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void autoCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoCheckBoxActionPerformed
        MemoryCheck.autoCall = this.autoCheckBox.isSelected();
    }//GEN-LAST:event_autoCheckBoxActionPerformed

    private void gcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gcButtonActionPerformed
        Runtime.getRuntime().gc();
        MemoryCheck.checker.check();
    }//GEN-LAST:event_gcButtonActionPerformed

    public static void showMemoryCheck() {
        if (instance == null) {
            instance = new MemoryCheck(null);
        }
        instance.setVisible(true);
    }

    public static class Checker extends Thread {

        @Override
        public void run() {
            try {
                while (true) {
                    Checker.this.check();
                    Thread.sleep(5000);
                }
            } catch (InterruptedException ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
            }
        }

        public void check() {
            Runtime r = Runtime.getRuntime();
            if (autoCall) {
                r.gc();
            }

            double usedMemory = (r.totalMemory() / 1024.0 / 1024.0) - (r.freeMemory() / 1024.0 / 1024.0);
            if (this.maxMemoryUsed < usedMemory) {
                this.maxMemoryUsed = usedMemory;
            }

            NumberFormat form = NumberFormat.getInstance();
            form.setMaximumFractionDigits(2);
            form.setMinimumFractionDigits(2);

            currentTextField.setText(form.format(usedMemory) + " MB");
            maximumTextField.setText(form.format(this.maxMemoryUsed) + " MB");
        }

        private double maxMemoryUsed = Double.MIN_VALUE;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
//                new MemoryCheck(new javax.swing.JFrame(), true).setVisible(true);
            }

        });
    }

    private static Checker checker;
    private static MemoryCheck instance;
    private static boolean autoCall;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox autoCheckBox;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JLabel currentLabel;
    private static javax.swing.JTextField currentTextField;
    private javax.swing.JButton gcButton;
    private javax.swing.JLabel maximumLabel;
    private static javax.swing.JTextField maximumTextField;
    private javax.swing.JPanel memoryPanel;
    // End of variables declaration//GEN-END:variables
}
