/* ***** BEGIN LICENSE BLOCK *****
 *
 * Copyright (c) 2005-2007 Universidade de Sao Paulo, Sao Carlos/SP, Brazil.
 * All Rights Reserved.
 *
 * This file is part of Projection Explorer (PEx).
 *
 * How to cite this work:
 *  
@inproceedings{paulovich2007pex,
author = {Fernando V. Paulovich and Maria Cristina F. Oliveira and Rosane 
Minghim},
title = {The Projection Explorer: A Flexible Tool for Projection-based 
Multidimensional Visualization},
booktitle = {SIBGRAPI '07: Proceedings of the XX Brazilian Symposium on 
Computer Graphics and Image Processing (SIBGRAPI 2007)},
year = {2007},
isbn = {0-7695-2996-8},
pages = {27--34},
doi = {http://dx.doi.org/10.1109/SIBGRAPI.2007.39},
publisher = {IEEE Computer Society},
address = {Washington, DC, USA},
}
 *  
 * PEx is free software: you can redistribute it and/or modify it under 
 * the terms of the GNU General Public License as published by the Free 
 * Software Foundation, either version 3 of the License, or (at your option) 
 * any later version.
 *
 * PEx is distributed in the hope that it will be useful, but WITHOUT 
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License 
 * for more details.
 *
 * This code was developed by members of Computer Graphics and Image
 * Processing Group (http://www.lcad.icmc.usp.br) at Instituto de Ciencias
 * Matematicas e de Computacao - ICMC - (http://www.icmc.usp.br) of 
 * Universidade de Sao Paulo, Sao Carlos/SP, Brazil. The initial developer 
 * of the original code is Roberto Pinho <robertopinho@yahoo.com.br>, 
 * Fernando Vieira Paulovich <fpaulovich@gmail.com>.
 *
 * Contributor(s): Rosane Minghim <rminghim@icmc.usp.br>
 *
 * You should have received a copy of the GNU General Public License along 
 * with PEx. If not, see <http://www.gnu.org/licenses/>.
 *
 * ***** END LICENSE BLOCK ***** */

package visualizer.topic;

import java.util.logging.Level;
import java.util.logging.Logger;
import visualizer.graph.Graph;
import visualizer.textprocessing.transformation.MatrixTransformationType;
import visualizer.textprocessing.stemmer.StemmerType;
import visualizer.util.OpenDialog;
import visualizer.view.tools.LuhnCutAnalizer;
import visualizer.topic.TopicData.ClusteringType;
import visualizer.topic.TopicData.WeightType;

/**
 *
 * @author  Fernando Vieira Paulovich
 */
public class TopicRuleTFSettings extends javax.swing.JDialog {

    /** Creates new form CreateScalarFromDoc */
    private TopicRuleTFSettings(javax.swing.JDialog parent) {
        super(parent);
        initComponents();

        for (StemmerType st : StemmerType.getTypes()) {
            this.stemmerComboBox.addItem(st);
        }
        
        for (MatrixTransformationType mtt : MatrixTransformationType.getTypes()) {
            this.matrixtransfComboBox.addItem(mtt);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        distanceButtonGroup = new javax.swing.ButtonGroup();
        matrixButtonGroup = new javax.swing.ButtonGroup();
        kolmoButtonGroup = new javax.swing.ButtonGroup();
        wordListButtonGroup = new javax.swing.ButtonGroup();
        clusteringButtonGroup = new javax.swing.ButtonGroup();
        dataPanel = new javax.swing.JPanel();
        preprocessingPanel = new javax.swing.JPanel();
        parametersPanel = new javax.swing.JPanel();
        luhnLowerLabel = new javax.swing.JLabel();
        gramsComboBox = new javax.swing.JComboBox();
        gramsLabel = new javax.swing.JLabel();
        luhnLowerTextField = new javax.swing.JTextField();
        analyzeButton = new javax.swing.JButton();
        luhnUpperLabel = new javax.swing.JLabel();
        luhnUpperTextField = new javax.swing.JTextField();
        stemmerComboBox = new javax.swing.JComboBox();
        matrixTypePanel = new javax.swing.JPanel();
        matrixtransfComboBox = new javax.swing.JComboBox();
        wordListTypePanel = new javax.swing.JPanel();
        stopRadioButton = new javax.swing.JRadioButton();
        startRadioButton = new javax.swing.JRadioButton();
        weightPanel = new javax.swing.JPanel();
        fMeasureRadioButton = new javax.swing.JRadioButton();
        localRadioButton = new javax.swing.JRadioButton();
        betaTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        clusteringPanel = new javax.swing.JPanel();
        kmeansRadioButton = new javax.swing.JRadioButton();
        dbscanRadioButton = new javax.swing.JRadioButton();
        labelStylePanel = new javax.swing.JPanel();
        groupLabelCheckBox = new javax.swing.JCheckBox();
        ruleLabelCheckBox = new javax.swing.JCheckBox();
        phraseLabelCheckBox = new javax.swing.JCheckBox();
        shortPhraseLabelCheckBox = new javax.swing.JCheckBox();
        supportPanel = new javax.swing.JPanel();
        absSupportCheckBox = new javax.swing.JCheckBox();
        absSupportText = new javax.swing.JTextField();
        buttonPanel = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();
        cancekButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Parameters to Create Label");
        setModal(true);

        dataPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Data"));
        dataPanel.setLayout(new java.awt.GridBagLayout());

        preprocessingPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Preprocessing"));
        preprocessingPanel.setLayout(new java.awt.GridBagLayout());

        parametersPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Parameters"));
        parametersPanel.setLayout(new java.awt.GridBagLayout());

        luhnLowerLabel.setText("Luhn's lower cut");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        parametersPanel.add(luhnLowerLabel, gridBagConstraints);

        gramsComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        parametersPanel.add(gramsComboBox, gridBagConstraints);

        gramsLabel.setText("Number of grams");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        parametersPanel.add(gramsLabel, gridBagConstraints);

        luhnLowerTextField.setColumns(5);
        luhnLowerTextField.setText("10");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        parametersPanel.add(luhnLowerTextField, gridBagConstraints);

        analyzeButton.setText("Analyze");
        analyzeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analyzeButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        parametersPanel.add(analyzeButton, gridBagConstraints);

        luhnUpperLabel.setText("Luhn's upper cut");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        parametersPanel.add(luhnUpperLabel, gridBagConstraints);

        luhnUpperTextField.setColumns(5);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        parametersPanel.add(luhnUpperTextField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        parametersPanel.add(stemmerComboBox, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        preprocessingPanel.add(parametersPanel, gridBagConstraints);

        matrixTypePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Matrix Transformation"));
        matrixTypePanel.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        matrixTypePanel.add(matrixtransfComboBox, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        preprocessingPanel.add(matrixTypePanel, gridBagConstraints);

        wordListTypePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Word List Type"));
        wordListTypePanel.setLayout(new java.awt.GridBagLayout());

        wordListButtonGroup.add(stopRadioButton);
        stopRadioButton.setText("Stop Words");
        stopRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        stopRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        wordListTypePanel.add(stopRadioButton, gridBagConstraints);

        wordListButtonGroup.add(startRadioButton);
        startRadioButton.setText("Start Words");
        startRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        startRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        wordListTypePanel.add(startRadioButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        preprocessingPanel.add(wordListTypePanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        dataPanel.add(preprocessingPanel, gridBagConstraints);

        weightPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Weight"));
        weightPanel.setLayout(new java.awt.GridBagLayout());

        distanceButtonGroup.add(fMeasureRadioButton);
        fMeasureRadioButton.setText("F-measure");
        fMeasureRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        fMeasureRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        weightPanel.add(fMeasureRadioButton, gridBagConstraints);

        distanceButtonGroup.add(localRadioButton);
        localRadioButton.setSelected(true);
        localRadioButton.setText("Local");
        localRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        localRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        weightPanel.add(localRadioButton, gridBagConstraints);

        betaTextField.setColumns(5);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        weightPanel.add(betaTextField, gridBagConstraints);

        jLabel1.setText("Beta");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        weightPanel.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        dataPanel.add(weightPanel, gridBagConstraints);

        clusteringPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Clustering Technique"));
        clusteringPanel.setLayout(new java.awt.GridBagLayout());

        clusteringButtonGroup.add(kmeansRadioButton);
        kmeansRadioButton.setSelected(true);
        kmeansRadioButton.setText("K-means");
        kmeansRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        kmeansRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        clusteringPanel.add(kmeansRadioButton, gridBagConstraints);

        clusteringButtonGroup.add(dbscanRadioButton);
        dbscanRadioButton.setText("DBSCAN");
        dbscanRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        dbscanRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        clusteringPanel.add(dbscanRadioButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        dataPanel.add(clusteringPanel, gridBagConstraints);

        labelStylePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Label Style"));
        labelStylePanel.setLayout(new java.awt.GridLayout(2, 0));

        groupLabelCheckBox.setText("Group Labels");
        groupLabelCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        groupLabelCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));
        groupLabelCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupLabelCheckBoxActionPerformed(evt);
            }
        });
        labelStylePanel.add(groupLabelCheckBox);

        ruleLabelCheckBox.setSelected(true);
        ruleLabelCheckBox.setText("Association Rule");
        ruleLabelCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        ruleLabelCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));
        ruleLabelCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruleLabelCheckBoxActionPerformed(evt);
            }
        });
        labelStylePanel.add(ruleLabelCheckBox);

        phraseLabelCheckBox.setText("Phrase");
        phraseLabelCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        phraseLabelCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));
        phraseLabelCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phraseLabelCheckBoxActionPerformed(evt);
            }
        });
        labelStylePanel.add(phraseLabelCheckBox);

        shortPhraseLabelCheckBox.setText("Short Phrase");
        shortPhraseLabelCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        shortPhraseLabelCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));
        labelStylePanel.add(shortPhraseLabelCheckBox);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        dataPanel.add(labelStylePanel, gridBagConstraints);

        supportPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Initial Minimun Support"));

        absSupportCheckBox.setText("Absolute Support:");
        supportPanel.add(absSupportCheckBox);

        absSupportText.setColumns(5);
        absSupportText.setText("5");
        supportPanel.add(absSupportText);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        dataPanel.add(supportPanel, gridBagConstraints);

        getContentPane().add(dataPanel, java.awt.BorderLayout.CENTER);

        closeButton.setText("OK");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(closeButton);

        cancekButton.setText("Cancel");
        cancekButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancekButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(cancekButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void phraseLabelCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phraseLabelCheckBoxActionPerformed
// TODO adicione seu código de manipulação aqui:
    }//GEN-LAST:event_phraseLabelCheckBoxActionPerformed

    private void ruleLabelCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruleLabelCheckBoxActionPerformed
// TODO adicione seu código de manipulação aqui:
    }//GEN-LAST:event_ruleLabelCheckBoxActionPerformed

    private void groupLabelCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupLabelCheckBoxActionPerformed
// TODO adicione seu código de manipulação aqui:
    }//GEN-LAST:event_groupLabelCheckBoxActionPerformed

    private void cancekButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancekButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancekButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.refreshData();
        OpenDialog.checkCorpus(this.graph, this);
        this.setVisible(false);
    }//GEN-LAST:event_closeButtonActionPerformed

    private void analyzeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analyzeButtonActionPerformed
        this.refreshData();
        OpenDialog.checkCorpus(this.graph, this);

        this.graph.getTopicData().setLunhLowerCut(Integer.parseInt(this.luhnLowerTextField.getText()));
        this.graph.getTopicData().setLunhUpperCut(-1);
        try {
            this.graph.getTopicData().setLunhUpperCut(Integer.parseInt(this.luhnUpperTextField.getText()));
        } catch (NumberFormatException ex) {
            Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
        }

        LuhnCutAnalizer.getInstance(this).display(this.graph.getProjectionData(), this.graph.getTopicData());

        this.luhnLowerTextField.setText(Integer.toString(this.graph.getTopicData().getLunhLowerCut()));
        this.luhnUpperTextField.setText(Integer.toString(this.graph.getTopicData().getLunhUpperCut()));
    }//GEN-LAST:event_analyzeButtonActionPerformed

    public static TopicRuleTFSettings getInstance(javax.swing.JDialog parent) {
        if (instance == null || instance.getParent() != parent) {
            instance = new TopicRuleTFSettings(parent);
        }
        return instance;
    }

    public void display(Graph graph) {
        this.graph = graph;

        TopicData tdata = graph.getTopicData();

        this.stemmerComboBox.setSelectedItem(tdata.getStemmer());
        this.groupLabelCheckBox.setSelected(tdata.isGroupTopics());
        this.ruleLabelCheckBox.setSelected(tdata.isRuleTopic());
        this.phraseLabelCheckBox.setSelected(tdata.isPhrase());
        this.shortPhraseLabelCheckBox.setSelected(tdata.isShortPhrase());
        this.absSupportCheckBox.setSelected(tdata.getSupportType() == TopicData.SupportType.ABSOLUTE);

        this.absSupportText.setText(Integer.toString(tdata.getMinSupAbs()));

        this.stopRadioButton.setSelected(tdata.isUseStopword());
        this.startRadioButton.setSelected(!tdata.isUseStopword());

        this.luhnLowerTextField.setText(Integer.toString(tdata.getLunhLowerCut()));
        if (tdata.getLunhUpperCut() == -1) {
            this.luhnUpperTextField.setText("");
        } else {
            this.luhnUpperTextField.setText(Integer.toString(tdata.getLunhUpperCut()));
        }

        this.gramsComboBox.setSelectedIndex(tdata.getNumberGrams() - 1);
        this.matrixtransfComboBox.setSelectedItem(tdata.getMatrixTransformationType());

        fMeasureRadioButton.setSelected(false);
        localRadioButton.setSelected(false);
        if (this.graph.getTopicData().getWeightType() == WeightType.F_MEASURE) {
            fMeasureRadioButton.setSelected(true);
        } else {
            localRadioButton.setSelected(true);
        }

        betaTextField.setText(this.graph.getTopicData().getWeightBeta().toString());

        kmeansRadioButton.setSelected(false);
        dbscanRadioButton.setSelected(false);
        if (this.graph.getTopicData().getClusteringType() == ClusteringType.KMEANS) {
            kmeansRadioButton.setSelected(true);
        } else {
            dbscanRadioButton.setSelected(true);
        }

        this.pack();
        this.setLocationRelativeTo(this.getParent());
        this.setVisible(true);
    }

    private void refreshData() {
        TopicData tdata = graph.getTopicData();

        tdata.setLunhLowerCut(Integer.parseInt(this.luhnLowerTextField.getText()));
        tdata.setStemmer((StemmerType) this.stemmerComboBox.getSelectedItem());
        tdata.setUseStopword(this.stopRadioButton.isSelected());
        tdata.setGroupTopics(groupLabelCheckBox.isSelected());
        tdata.setRuleTopic(ruleLabelCheckBox.isSelected());
        tdata.setPhrase(phraseLabelCheckBox.isSelected());
        tdata.setShortPhrase(shortPhraseLabelCheckBox.isSelected());

        if (absSupportCheckBox.isSelected()) {
            tdata.setSupportType(TopicData.SupportType.ABSOLUTE);
            tdata.setMinSupAbs(new Integer(absSupportText.getText()).intValue());
        } else {
            tdata.setSupportType(TopicData.SupportType.RELATIVE);
        }
        if (this.luhnUpperTextField.getText().trim().length() > 0) {
            tdata.setLunhUpperCut(Integer.parseInt(this.luhnUpperTextField.getText()));
        } else {
            tdata.setLunhUpperCut(-1);
        }

        tdata.setNumberGrams(this.gramsComboBox.getSelectedIndex() + 1);
        tdata.setMatrixTransformationType((MatrixTransformationType) this.matrixtransfComboBox.getSelectedItem());
        
        if (kmeansRadioButton.isSelected()) {
            tdata.setClusteringType(ClusteringType.KMEANS);
        } else {
            tdata.setClusteringType(ClusteringType.DBSCAN);
        }

        tdata.setWeightBeta(new Float(betaTextField.getText()));
        if (localRadioButton.isSelected()) {
            tdata.setWeightType(WeightType.LOCAL);
        } else {
            tdata.setWeightType(WeightType.F_MEASURE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TopicRuleTFSettings(new javax.swing.JDialog()).setVisible(true);
            }

        });
    }

    private static TopicRuleTFSettings instance;
    private Graph graph;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox absSupportCheckBox;
    private javax.swing.JTextField absSupportText;
    private javax.swing.JButton analyzeButton;
    private javax.swing.JTextField betaTextField;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancekButton;
    private javax.swing.JButton closeButton;
    private javax.swing.ButtonGroup clusteringButtonGroup;
    private javax.swing.JPanel clusteringPanel;
    private javax.swing.JPanel dataPanel;
    private javax.swing.JRadioButton dbscanRadioButton;
    private javax.swing.ButtonGroup distanceButtonGroup;
    private javax.swing.JRadioButton fMeasureRadioButton;
    private javax.swing.JComboBox gramsComboBox;
    private javax.swing.JLabel gramsLabel;
    private javax.swing.JCheckBox groupLabelCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton kmeansRadioButton;
    private javax.swing.ButtonGroup kolmoButtonGroup;
    private javax.swing.JPanel labelStylePanel;
    private javax.swing.JRadioButton localRadioButton;
    private javax.swing.JLabel luhnLowerLabel;
    private javax.swing.JTextField luhnLowerTextField;
    private javax.swing.JLabel luhnUpperLabel;
    private javax.swing.JTextField luhnUpperTextField;
    private javax.swing.ButtonGroup matrixButtonGroup;
    private javax.swing.JPanel matrixTypePanel;
    private javax.swing.JComboBox matrixtransfComboBox;
    private javax.swing.JPanel parametersPanel;
    private javax.swing.JCheckBox phraseLabelCheckBox;
    private javax.swing.JPanel preprocessingPanel;
    private javax.swing.JCheckBox ruleLabelCheckBox;
    private javax.swing.JCheckBox shortPhraseLabelCheckBox;
    private javax.swing.JRadioButton startRadioButton;
    private javax.swing.JComboBox stemmerComboBox;
    private javax.swing.JRadioButton stopRadioButton;
    private javax.swing.JPanel supportPanel;
    private javax.swing.JPanel weightPanel;
    private javax.swing.ButtonGroup wordListButtonGroup;
    private javax.swing.JPanel wordListTypePanel;
    // End of variables declaration//GEN-END:variables
}
