/*
 * FeatureSelectionView.java
 *
 * Created on 6 de Maio de 2008, 08:35
 */
package visualizer.featureselection;

import java.io.BufferedInputStream;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.StringTokenizer;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import visualizer.util.OpenDialog;
import visualizer.util.SaveDialog;
import visualizer.util.SystemPropertiesManager;
import visualizer.util.filefilter.DATAFilter;
import visualizer.util.filefilter.WEIGHTFilter;

/**
 *
 * @author  Danilo M Eler
 */


public class FeatureSelectionView extends javax.swing.JFrame {

    /** Creates new form FeatureSelectionView */
   
    public FeatureSelectionView() {
        initComponents();
        initModels();
        this.selectedFeaturesjTable.setModel(selectedFeaturesTableModel);
        this.discardedFeaturesjTable.setModel(discardedFeaturesTableModel);
        this.rankedFeaturesjTable.setModel(salienceTableModel);

    }

    private void initModels() {
        String[] featureTitles;
        String[] salienceTitles;

        featureTitles = new String[]{"Features"};
        salienceTitles = new String[]{"Features", "Salience"};

        this.selectedFeaturesTableModel = new DefaultTableModel(null, featureTitles);
        this.discardedFeaturesTableModel = new DefaultTableModel(null, featureTitles);
        this.salienceTableModel = new DefaultTableModel(null, salienceTitles);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      training_jPanel = new javax.swing.JPanel();
      jLabel1 = new javax.swing.JLabel();
      trainingButton = new javax.swing.JButton();
      trainingTextField = new javax.swing.JTextField();
      jScrollPane1 = new javax.swing.JScrollPane();
      trainingOutput_jTA = new javax.swing.JTextArea();
      execTraining_jButton = new javax.swing.JButton();
      stopTraining_jButton = new javax.swing.JButton();
      normalizejCheckBox = new javax.swing.JCheckBox();
      training_jPanel1 = new javax.swing.JPanel();
      jLabel2 = new javax.swing.JLabel();
      weightButton = new javax.swing.JButton();
      weightTextField = new javax.swing.JTextField();
      execRanking_jButton = new javax.swing.JButton();
      jLabel3 = new javax.swing.JLabel();
      numClassesjTextField = new javax.swing.JTextField();
      jLabel4 = new javax.swing.JLabel();
      numFeaturesjTextField = new javax.swing.JTextField();
      jLabel5 = new javax.swing.JLabel();
      pointsTextField = new javax.swing.JTextField();
      pointsButton = new javax.swing.JButton();
      jPanel1 = new javax.swing.JPanel();
      selectedFeaturesjScrollPane = new javax.swing.JScrollPane();
      selectedFeaturesjTable = new javax.swing.JTable();
      featureRankingjScrollPane = new javax.swing.JScrollPane();
      rankedFeaturesjTable = new javax.swing.JTable();
      discardedFeaturesJScrollPane = new javax.swing.JScrollPane();
      discardedFeaturesjTable = new javax.swing.JTable();
      AddFeature = new javax.swing.JButton();
      RemoveFeature = new javax.swing.JButton();
      saveToPExjButton = new javax.swing.JButton();
      DiscardedFeatures_ClearSelection = new javax.swing.JButton();
      SelectedFeatures_SelectAll = new javax.swing.JButton();
      RankingFeature_ClearSelection = new javax.swing.JButton();
      RankingFeature_SelectAll = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      training_jPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Neural Network Training"));

      jLabel1.setText("Points File");

      trainingButton.setText("Search...");
      trainingButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            trainingButtonActionPerformed(evt);
         }
      });

      trainingTextField.setColumns(35);

      trainingOutput_jTA.setColumns(20);
      trainingOutput_jTA.setRows(5);
      jScrollPane1.setViewportView(trainingOutput_jTA);

      execTraining_jButton.setText("Execute Training");
      execTraining_jButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            execTraining_jButtonActionPerformed(evt);
         }
      });

      stopTraining_jButton.setText("Stop Training");
      stopTraining_jButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            stopTraining_jButtonActionPerformed(evt);
         }
      });

      normalizejCheckBox.setText("Normalize Before Training");

      javax.swing.GroupLayout training_jPanelLayout = new javax.swing.GroupLayout(training_jPanel);
      training_jPanel.setLayout(training_jPanelLayout);
      training_jPanelLayout.setHorizontalGroup(
         training_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(training_jPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(training_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(training_jPanelLayout.createSequentialGroup()
                  .addComponent(jLabel1)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(trainingTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE))
               .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(training_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(trainingButton, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
               .addComponent(stopTraining_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
               .addComponent(execTraining_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
               .addComponent(normalizejCheckBox))
            .addContainerGap())
      );
      training_jPanelLayout.setVerticalGroup(
         training_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(training_jPanelLayout.createSequentialGroup()
            .addGroup(training_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel1)
               .addComponent(trainingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(trainingButton))
            .addGap(14, 14, 14)
            .addGroup(training_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
               .addGroup(training_jPanelLayout.createSequentialGroup()
                  .addComponent(normalizejCheckBox)
                  .addGap(17, 17, 17)
                  .addComponent(execTraining_jButton)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(stopTraining_jButton)))
            .addContainerGap())
      );

      training_jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Feature Ranking"));

      jLabel2.setText("Weight File");

      weightButton.setText("Search...");
      weightButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            weightButtonActionPerformed(evt);
         }
      });

      weightTextField.setColumns(35);

      execRanking_jButton.setText("Execute Ranking");
      execRanking_jButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            execRanking_jButtonActionPerformed(evt);
         }
      });

      jLabel3.setText("Number of Classes");

      numClassesjTextField.setText("0");

      jLabel4.setText("Number of Features");

      numFeaturesjTextField.setText("0");

      jLabel5.setText("Points File");

      pointsTextField.setColumns(35);

      pointsButton.setText("Search...");
      pointsButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            pointsButtonActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout training_jPanel1Layout = new javax.swing.GroupLayout(training_jPanel1);
      training_jPanel1.setLayout(training_jPanel1Layout);
      training_jPanel1Layout.setHorizontalGroup(
         training_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(training_jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(training_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(training_jPanel1Layout.createSequentialGroup()
                  .addComponent(jLabel3)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(numClassesjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addComponent(jLabel4)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(numFeaturesjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(execRanking_jButton))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, training_jPanel1Layout.createSequentialGroup()
                  .addGroup(training_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                     .addGroup(javax.swing.GroupLayout.Alignment.LEADING, training_jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pointsTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE))
                     .addGroup(training_jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(weightTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(training_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(weightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(pointsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addContainerGap())
      );
      training_jPanel1Layout.setVerticalGroup(
         training_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(training_jPanel1Layout.createSequentialGroup()
            .addGroup(training_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel2)
               .addComponent(weightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(weightButton))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(training_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel5)
               .addComponent(pointsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(pointsButton))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(training_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel3)
               .addComponent(numClassesjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel4)
               .addComponent(numFeaturesjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(execRanking_jButton))
            .addContainerGap(12, Short.MAX_VALUE))
      );

      jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Feature Selection"));
      jPanel1.setLayout(null);

      selectedFeaturesjScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Selected Features"));

      selectedFeaturesjTable.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {

         },
         new String [] {
            "Feature"
         }
      ) {
         Class[] types = new Class [] {
            java.lang.String.class
         };
         boolean[] canEdit = new boolean [] {
            false
         };

         public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
         }

         public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
         }
      });
      selectedFeaturesjTable.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            selectedFeaturesjTableMouseClicked(evt);
         }
      });
      selectedFeaturesjScrollPane.setViewportView(selectedFeaturesjTable);

      jPanel1.add(selectedFeaturesjScrollPane);
      selectedFeaturesjScrollPane.setBounds(10, 30, 150, 300);

      featureRankingjScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Feature Ranking"));

      rankedFeaturesjTable.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {

         },
         new String [] {
            "Feature", "Salience"
         }
      ) {
         Class[] types = new Class [] {
            java.lang.String.class, java.lang.Double.class
         };

         public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
         }
      });
      featureRankingjScrollPane.setViewportView(rankedFeaturesjTable);

      jPanel1.add(featureRankingjScrollPane);
      featureRankingjScrollPane.setBounds(380, 30, 150, 300);

      discardedFeaturesJScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Discarded Features"));

      discardedFeaturesjTable.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {

         },
         new String [] {
            "Feature"
         }
      ) {
         Class[] types = new Class [] {
            java.lang.String.class
         };
         boolean[] canEdit = new boolean [] {
            false
         };

         public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
         }

         public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
         }
      });
      discardedFeaturesJScrollPane.setViewportView(discardedFeaturesjTable);

      jPanel1.add(discardedFeaturesJScrollPane);
      discardedFeaturesJScrollPane.setBounds(220, 30, 150, 300);

      AddFeature.setText("<<");
      AddFeature.setToolTipText("Add Selected Features");
      AddFeature.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            AddFeatureActionPerformed(evt);
         }
      });
      jPanel1.add(AddFeature);
      AddFeature.setBounds(163, 130, 50, 23);

      RemoveFeature.setText(">>");
      RemoveFeature.setToolTipText("Remove Selected Features");
      RemoveFeature.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            RemoveFeatureActionPerformed(evt);
         }
      });
      jPanel1.add(RemoveFeature);
      RemoveFeature.setBounds(163, 100, 50, 23);

      saveToPExjButton.setText("Save Points to PEx-Image");
      saveToPExjButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            saveToPExjButtonActionPerformed(evt);
         }
      });
      jPanel1.add(saveToPExjButton);
      saveToPExjButton.setBounds(540, 90, 180, 23);

      DiscardedFeatures_ClearSelection.setText("Clear");
      DiscardedFeatures_ClearSelection.setToolTipText("Clear All Selected Features");
      DiscardedFeatures_ClearSelection.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            DiscardedFeatures_ClearSelectionActionPerformed(evt);
         }
      });
      jPanel1.add(DiscardedFeatures_ClearSelection);
      DiscardedFeatures_ClearSelection.setBounds(300, 330, 70, 23);

      SelectedFeatures_SelectAll.setText("All");
      SelectedFeatures_SelectAll.setToolTipText("Select All");
      SelectedFeatures_SelectAll.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            SelectedFeatures_SelectAllActionPerformed(evt);
         }
      });
      jPanel1.add(SelectedFeatures_SelectAll);
      SelectedFeatures_SelectAll.setBounds(90, 330, 70, 23);

      RankingFeature_ClearSelection.setText("Clear");
      RankingFeature_ClearSelection.setToolTipText("Clear All Selected Features");
      RankingFeature_ClearSelection.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            RankingFeature_ClearSelectionActionPerformed(evt);
         }
      });
      jPanel1.add(RankingFeature_ClearSelection);
      RankingFeature_ClearSelection.setBounds(460, 330, 70, 23);

      RankingFeature_SelectAll.setText("All");
      RankingFeature_SelectAll.setToolTipText("Select All");
      RankingFeature_SelectAll.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            RankingFeature_SelectAllActionPerformed(evt);
         }
      });
      jPanel1.add(RankingFeature_SelectAll);
      RankingFeature_SelectAll.setBounds(380, 330, 70, 23);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
               .addComponent(training_jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(training_jPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(training_jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(training_jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents
    private void trainingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainingButtonActionPerformed
        int result = OpenDialog.showOpenDialog(new DATAFilter(), this);

        if (result == JFileChooser.APPROVE_OPTION) {
            this.trainingFilename = OpenDialog.getFilename();
            this.trainingTextField.setText(trainingFilename);
        }
        
}//GEN-LAST:event_trainingButtonActionPerformed

    private SalienceSelectorThread Execute;
    
    private void execTraining_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_execTraining_jButtonActionPerformed
        if(!trainingTextField.getText().equals("")){
        
        // Comandos para executar a partir do prompt. 
        String fDir = SystemPropertiesManager.getInstance().getProperty("FEATURE.DIR");
        //trainingOutput_jTA.setText("It is not working correctly. Please Execute: \n");       
        
        String classFile = trainingTextField.getText().substring(trainingTextField.getText().lastIndexOf("\\")+1, trainingTextField.getText().lastIndexOf("."));
        classFile = classFile + ".classes";
                
        String normalize = "notNormalize";
        if (normalizejCheckBox.isSelected()){
            normalize = "normal";
        }
        
        trainingOutput_jTA.append("Executing: \"" + fDir + "\\programa-seletor-saliencia-puro.exe\" " + "\"" + trainingTextField.getText() + "\" " + classFile + " " + normalize + " \n");
        
        Execute = new SalienceSelectorThread("\"" + fDir + "\\programa-seletor-saliencia-puro.exe\" " + "\"" + trainingTextField.getText() + "\" " + classFile + " " + normalize);
        Execute.start();

        trainingOutput_jTA.append("Path for Weight Files: " + "\"" + System.getProperty("user.dir") + "\"\n");
        trainingOutput_jTA.append("Path for Classes File: " + "\"" + System.getProperty("user.dir") + "\\" + classFile + "\"\n\n");
        }
    }//GEN-LAST:event_execTraining_jButtonActionPerformed

    private void weightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightButtonActionPerformed
        // TODO add your handling code here:
        int result = OpenDialog.showOpenDialog(new WEIGHTFilter(), this);

        if (result == JFileChooser.APPROVE_OPTION) {
            this.weightFilename = OpenDialog.getFilename();
            this.weightTextField.setText(weightFilename);
        }
        BufferedReader pFile = null;
        try
        {
           pFile = new BufferedReader(new java.io.FileReader(this.weightTextField.getText()));
           String Line = pFile.readLine();
           this.numFeaturesjTextField.setText(Line);
           Line = pFile.readLine();
           Line = pFile.readLine();
           StringTokenizer Token = new StringTokenizer(Line, " ");
           this.numClassesjTextField.setText(Token.nextToken());
        }
        catch (FileNotFoundException e) 
        {
            //new java.io.IOException("File " + filename + " does not exist!");
            e.printStackTrace();
        } catch (java.io.IOException e) 
        {
            //throw new java.io.IOException("Problems reading the file " + filename + " : " + e.getMessage());
            e.printStackTrace();
        } finally 
        {
            //fechar o arquivo
            if (pFile != null) {
                try {
                    pFile.close();
                } catch (IOException e1) {
                    e1.printStackTrace();
                }
            }
        }
}//GEN-LAST:event_weightButtonActionPerformed

    private void pointsReader(String filename) {
        java.util.Vector<java.util.Vector<Float>> points = new java.util.Vector<java.util.Vector<Float>>();
        this.attributes = new java.util.Vector<String>();

        BufferedReader in = null;
        try {
            in = new BufferedReader(new java.io.FileReader(filename));
            String line = null;

            //Read the attributes
            while ((line = in.readLine()) != null && line.trim().length() > 1) {
                //Ignore comments
                if (line.lastIndexOf('#') == -1) {
                    StringTokenizer t = new StringTokenizer(line, ";");

                    while (t.hasMoreTokens()) {
                        String token = t.nextToken();
                        this.attributes.add(token.trim());
                    }
                    break;
                }
            }
            //Read the points
            while ((line = in.readLine()) != null && line.trim().length() > 1) {
                //Ignore comments
                if (line.lastIndexOf('#') == -1) {
                    StringTokenizer t = new StringTokenizer(line, ";");

                    java.util.Vector<Float> point = new java.util.Vector<Float>();

                    while (t.hasMoreTokens()) {
                        String token = t.nextToken();
                        point.add(Float.parseFloat(token));
                    }
                    points.add(point);
                }
            }

            this.originalPoints = new float[points.size()][];
            for (int i = 0; i < points.size(); i++) {
                this.originalPoints[i] = new float[points.elementAt(i).size()];
                for (int j = 0; j < points.elementAt(i).size(); j++) {
                    this.originalPoints[i][j] = points.elementAt(i).elementAt(j);
                }
            }

        } catch (FileNotFoundException e) {
            //new java.io.IOException("File " + filename + " does not exist!");
            e.printStackTrace();
        } catch (java.io.IOException e) {
            //throw new java.io.IOException("Problems reading the file " + filename + " : " + e.getMessage());
            e.printStackTrace();
        } finally {
            //fechar o arquivo
            if (in != null) {
                try {
                    in.close();
                } catch (IOException e1) {
                    e1.printStackTrace();
                }
            }
        }
    }

    private void refreshTables() {
        int i;
        //this.selectedFeaturesjTable.removeAll();
        //this.discardedFeaturesjTable.removeAll();
        initModels();
        this.selectedFeaturesjTable.setModel(selectedFeaturesTableModel);
        this.discardedFeaturesjTable.setModel(discardedFeaturesTableModel);
        /*for (i=0; i<this.selectedFeaturesTableModel.getRowCount(); i++)
        this.selectedFeaturesTableModel.removeRow(i);
        for (i=0; i<this.discardedFeaturesTableModel.getRowCount(); i++)
        this.discardedFeaturesTableModel.removeRow(i);
         */
        String row[] = new String[1];
        String selAtt[] = this.pSel.getSelectedAttributes();
        String disAtt[] = this.pSel.getDiscardedAttributes();
        
        for (i = 0; i < selAtt.length - 1; i++) {
            row[0] = selAtt[i];
            this.selectedFeaturesTableModel.addRow(row);
        }

        for (i = 0; i < disAtt.length; i++) {
            row[0] = disAtt[i];
            this.discardedFeaturesTableModel.addRow(row);
        }
    }

    public void savePointsToPEx(String filename, float[][] points, String attributes[]) {
        BufferedWriter out = null;

        //SAVE THE POINTS FILE
        try {
            out = new BufferedWriter(new FileWriter(filename));

            //Writting the file header
            out.write("#Number objects: ");
            out.write(Integer.toString(points.length));
            out.write("\n");
            out.write("#Number dimensions: ");       //-1 to ignore the class
            out.write(Integer.toString(points[0].length - 1));
            out.write("\n");

            //writting the attributes
            if (attributes != null) {
                for (int i = 0; i < attributes.length - 1; i++) {
                    out.write(attributes[i].trim());
                    out.write(";");
                }
                out.write(attributes[attributes.length - 1].trim());
                out.write("\n");
            } else {
                for (int i = 0; i < attributes.length - 1; i++) {
                    out.write("attr" + i);
                    out.write(";");
                }
                out.write("attr" + (attributes.length - 1));
                out.write("\n");
            }

            for (int i = 0; i < points.length; i++) {
                for (int j = 0; j < points[i].length - 1; j++) {
                    out.write(Float.toString(points[i][j]));
                    out.write(";");
                }
                out.write(Float.toString(points[i][points[i].length - 1]));
                out.write("\n");
            }

        } catch (java.io.IOException e) {
            //throw new java.io.IOException("Problems written \"" + this.filename + "\"!");
            e.printStackTrace();
        } finally {
            //fechar o arquivo
            if (out != null) {
                try {
                    out.flush();
                    out.close();
                } catch (java.io.IOException e1) {
                    e1.printStackTrace();
                }
            }
        }
    }

    public void savePointsToClassifier(String filename, float[][] points) {
        BufferedWriter out = null;

        //SAVE THE POINTS FILE
        try {
            out = new BufferedWriter(new FileWriter(filename));

            //Writting the file header
            out.write("objects: ");
            out.write(Integer.toString(points.length));
            out.write("\n");
            out.write("dimensions: ");       //-1 to ignore the class
            out.write(Integer.toString(points[0].length - 1));
            out.write("\n");

            for (int i = 0; i < points.length; i++) {
                for (int j = 0; j < points[i].length; j++) {
                    out.write(Float.toString(points[i][j]));
                    out.write(" ");
                }                
                out.write("\n");
            }

        } catch (java.io.IOException e) {
            //throw new java.io.IOException("Problems written \"" + this.filename + "\"!");
            e.printStackTrace();
        } finally {
            //fechar o arquivo
            if (out != null) {
                try {
                    out.flush();
                    out.close();
                } catch (java.io.IOException e1) {
                    e1.printStackTrace();
                }
            }
        }
    }

    
    private void fillTables() {
        //prepare points to selection
        if (pointsFilename.equals("")){ 
            int result = OpenDialog.showOpenDialog(new DATAFilter(), this);

            if (result == JFileChooser.APPROVE_OPTION) {
                this.pointsFilename = OpenDialog.getFilename();
                this.pointsTextField.setText(pointsFilename);
                //String pointsFilename=OpenDialog.getJFileChooser().getSelectedFile().getName();
                this.namesFilename = pointsFilename.substring(0, pointsFilename.lastIndexOf('.')) + ".names";

            }            
            
        }
                pointsReader(pointsFilename);
                if (pSel == null) {
                    String temp[] = new String[this.attributes.size()];
                    for (int k = 0; k < this.attributes.size(); k++) {
                        temp[k] = this.attributes.get(k);
                    }
                    pSel = new PointsSelection(this.originalPoints, temp);
                }

                //fill ranking table
                String[] row = new String[2];
                for (int i = 0; i < features.size(); i++) {
                    row[0] = this.attributes.get(features.get(i));//String.valueOf(features.get(i));
                    row[1] = String.valueOf(saliences.get(i));
                    salienceTableModel.addRow(row);
                }
                refreshTables();          
        
    }

    private void execRanking_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_execRanking_jButtonActionPerformed
        // TODO add your handling code here:
        Process proc = null;
        Scanner in = null;
        try {
            System.out.println("INICIO - Executando Programa");
            String fDir = SystemPropertiesManager.getInstance().getProperty("FEATURE.DIR");
            
            System.out.println(fDir + "\\programa-ranking-saliencias-puro.exe " +
                    "\""+ this.weightTextField.getText() + "\"" +
                    this.numClassesjTextField.getText() + " " +
                    this.numFeaturesjTextField.getText());
            proc = new ProcessBuilder(fDir + "\\programa-ranking-saliencias-puro.exe ",
                    "\""+this.weightTextField.getText()+"\"",
                    this.numClassesjTextField.getText(),
                    this.numFeaturesjTextField.getText()).start();
            System.out.println("FIM - Executando Programa");

            in = new Scanner(new BufferedInputStream(proc.getInputStream()));
            System.out.println("Inicio - lendo saída de programa");
            while (in.hasNextLine() && !in.nextLine().equals("##########")) {
            }

            features.clear();
            saliences.clear();
            if (in.hasNextLine()) {
                features.clear();
                saliences.clear();
                int cID;
                double sali;
                String line = in.nextLine();
                while (in.hasNextLine() && !line.equals("##########")) {
                    //System.out.println(line);
                    cID = Integer.valueOf(line.substring(0, line.lastIndexOf('-')).trim());
                    sali = Double.valueOf(line.substring(line.lastIndexOf('-') + 1, line.length()).trim());
                    features.add(cID);
                    saliences.add(sali);
                    //System.out.println("cID: " + cID);
                    //System.out.println("sali: " + sali);
                    line = in.nextLine();
                }
            }
            System.out.println("Fim - lendo saída de programa");

            in.close();

        } catch (IOException ex) {
            ex.printStackTrace();
        } finally {
            if (proc != null) {
                proc.destroy();
            }

            if (in != null) {
                in.close();
            }

            if (features.size() > 0) {
                fillTables();
            }
        }
}//GEN-LAST:event_execRanking_jButtonActionPerformed

    private void selectedFeaturesjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectedFeaturesjTableMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            int index = this.selectedFeaturesjTable.getSelectedRow();
            if (index > -1) {
                String feature = (String) this.selectedFeaturesjTable.getValueAt(index, 0);
                this.pSel.discardAttribute(feature);
                refreshTables();
            }
        }
    }//GEN-LAST:event_selectedFeaturesjTableMouseClicked

    private void RemoveFeatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveFeatureActionPerformed
        // TODO add your handling code here:
        int index[] = this.selectedFeaturesjTable.getSelectedRows();
        if (index != null) 
        {
            for(int i = 0; i < this.selectedFeaturesjTable.getSelectedRowCount(); i++)
            {
               String feature = (String) this.selectedFeaturesjTable.getValueAt(index[i], 0);
               this.pSel.discardAttribute(feature);
            }
            refreshTables();
        }
}//GEN-LAST:event_RemoveFeatureActionPerformed

    private void AddFeatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFeatureActionPerformed
        // TODO add your handling code here:
        int DiscardedIndex[] = this.discardedFeaturesjTable.getSelectedRows();
        int RankedIndex[] = this.rankedFeaturesjTable.getSelectedRows();
        
        if (DiscardedIndex != null) 
        {
            for(int i = 0; i < this.discardedFeaturesjTable.getSelectedRowCount(); i++)
            {
               String feature = (String) this.discardedFeaturesjTable.getValueAt(DiscardedIndex[i], 0);
               this.pSel.selectAttribute(feature);
            }
            refreshTables();
        }
        
        if (RankedIndex != null)
        {
            for(int i = 0; i < this.rankedFeaturesjTable.getSelectedRowCount(); i++)
            {
               String feature = (String) this.rankedFeaturesjTable.getValueAt(RankedIndex[i], 0);
               this.pSel.selectAttribute(feature);
            }
            refreshTables();
        }
}//GEN-LAST:event_AddFeatureActionPerformed

    private void saveToPExjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveToPExjButtonActionPerformed
        // TODO add your handling code here:
        int result = SaveDialog.showSaveDialog(new DATAFilter(), this);

        if (result == JFileChooser.APPROVE_OPTION) {
            String filename = SaveDialog.getFilename();

            if (!filename.toLowerCase().endsWith(".data")) {
                filename = filename.concat(".data");
            }
            savePointsToPEx(filename, this.pSel.getSelectedPoints(), this.pSel.getSelectedAttributes());
        }
    }//GEN-LAST:event_saveToPExjButtonActionPerformed

    private void pointsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pointsButtonActionPerformed
        // TODO add your handling code here:
        int result = OpenDialog.showOpenDialog(new DATAFilter(), this);

        if (result == JFileChooser.APPROVE_OPTION) {
            this.pointsFilename = OpenDialog.getFilename();
            this.pointsTextField.setText(pointsFilename);
            //String pointsFilename=OpenDialog.getJFileChooser().getSelectedFile().getName();
            this.namesFilename = pointsFilename.substring(0, pointsFilename.lastIndexOf('.')) + ".names";
        }
}//GEN-LAST:event_pointsButtonActionPerformed

    private void SelectedFeatures_SelectAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectedFeatures_SelectAllActionPerformed
       // TODO add your handling code here:
       this.selectedFeaturesjTable.selectAll();
}//GEN-LAST:event_SelectedFeatures_SelectAllActionPerformed

    private void RankingFeature_SelectAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RankingFeature_SelectAllActionPerformed
       // TODO add your handling code here:
       this.rankedFeaturesjTable.selectAll();
}//GEN-LAST:event_RankingFeature_SelectAllActionPerformed

    private void DiscardedFeatures_ClearSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiscardedFeatures_ClearSelectionActionPerformed
       // TODO add your handling code here:
       this.discardedFeaturesjTable.clearSelection();
}//GEN-LAST:event_DiscardedFeatures_ClearSelectionActionPerformed

    private void RankingFeature_ClearSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RankingFeature_ClearSelectionActionPerformed
       // TODO add your handling code here:
       this.rankedFeaturesjTable.clearSelection();
}//GEN-LAST:event_RankingFeature_ClearSelectionActionPerformed

    private void stopTraining_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopTraining_jButtonActionPerformed
       // TODO add your handling code here:
       if(Execute.isAlive())
         Execute.StopProcess();
}//GEN-LAST:event_stopTraining_jButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FeatureSelectionView().setVisible(true);
            }
        });
    }
    
    public static void setTextArea(String AppendText)
    {
      trainingOutput_jTA.append(AppendText);
      trainingOutput_jTA.setCaretPosition(trainingOutput_jTA.getText().length());
    }
    
    String pointsFilename = "";
    String namesFilename = "";
    String weightFilename = "";
    String trainingFilename = "";
    DefaultTableModel selectedFeaturesTableModel;
    DefaultTableModel discardedFeaturesTableModel;
    DefaultTableModel salienceTableModel;
    PointsSelection pSel = null;
    float originalPoints[][];
    Vector<String> attributes = new Vector<String>();
    Vector<Integer> features = new Vector<Integer>();
    Vector<Double> saliences = new Vector<Double>();
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton AddFeature;
   private javax.swing.JButton DiscardedFeatures_ClearSelection;
   private javax.swing.JButton RankingFeature_ClearSelection;
   private javax.swing.JButton RankingFeature_SelectAll;
   private javax.swing.JButton RemoveFeature;
   private javax.swing.JButton SelectedFeatures_SelectAll;
   private javax.swing.JScrollPane discardedFeaturesJScrollPane;
   private javax.swing.JTable discardedFeaturesjTable;
   private javax.swing.JButton execRanking_jButton;
   private javax.swing.JButton execTraining_jButton;
   private javax.swing.JScrollPane featureRankingjScrollPane;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JCheckBox normalizejCheckBox;
   private javax.swing.JTextField numClassesjTextField;
   private javax.swing.JTextField numFeaturesjTextField;
   private javax.swing.JButton pointsButton;
   private javax.swing.JTextField pointsTextField;
   private javax.swing.JTable rankedFeaturesjTable;
   private javax.swing.JButton saveToPExjButton;
   private javax.swing.JScrollPane selectedFeaturesjScrollPane;
   private javax.swing.JTable selectedFeaturesjTable;
   private javax.swing.JButton stopTraining_jButton;
   private javax.swing.JButton trainingButton;
   private static javax.swing.JTextArea trainingOutput_jTA;
   private javax.swing.JTextField trainingTextField;
   private javax.swing.JPanel training_jPanel;
   private javax.swing.JPanel training_jPanel1;
   private javax.swing.JButton weightButton;
   private javax.swing.JTextField weightTextField;
   // End of variables declaration//GEN-END:variables
}
