/* ***** BEGIN LICENSE BLOCK *****
 *
 * Copyright (c) 2005-2007 Universidade de Sao Paulo, Sao Carlos/SP, Brazil.
 * All Rights Reserved.
 *
 * This file is part of Projection Explorer (PEx).
 *
 * How to cite this work:
 *  
@inproceedings{paulovich2007pex,
author = {Fernando V. Paulovich and Maria Cristina F. Oliveira and Rosane 
Minghim},
title = {The Projection Explorer: A Flexible Tool for Projection-based 
Multidimensional Visualization},
booktitle = {SIBGRAPI '07: Proceedings of the XX Brazilian Symposium on 
Computer Graphics and Image Processing (SIBGRAPI 2007)},
year = {2007},
isbn = {0-7695-2996-8},
pages = {27--34},
doi = {http://dx.doi.org/10.1109/SIBGRAPI.2007.39},
publisher = {IEEE Computer Society},
address = {Washington, DC, USA},
}
 *  
 * PEx is free software: you can redistribute it and/or modify it under 
 * the terms of the GNU General Public License as published by the Free 
 * Software Foundation, either version 3 of the License, or (at your option) 
 * any later version.
 *
 * PEx is distributed in the hope that it will be useful, but WITHOUT 
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License 
 * for more details.
 *
 * This code was developed by members of Computer Graphics and Image
 * Processing Group (http://www.lcad.icmc.usp.br) at Instituto de Ciencias
 * Matematicas e de Computacao - ICMC - (http://www.icmc.usp.br) of 
 * Universidade de Sao Paulo, Sao Carlos/SP, Brazil. The initial developer 
 * of the original code is Fernando Vieira Paulovich <fpaulovich@gmail.com>.
 *
 * Contributor(s): Roberto Pinho <robertopinho@yahoo.com.br>, 
 *                 Rosane Minghim <rminghim@icmc.usp.br>
 *
 * You should have received a copy of the GNU General Public License along 
 * with PEx. If not, see <http://www.gnu.org/licenses/>.
 *
 * ***** END LICENSE BLOCK ***** */

package visualizer.wizard;

import visualizer.projection.ProjectionData;
import visualizer.textprocessing.transformation.MatrixTransformationType;
import visualizer.textprocessing.stemmer.StemmerType;
import visualizer.view.tools.LuhnCutAnalizer;

/**
 *
 * @author  Fernando Vieira Paulovich
 */
public class Preprocessing extends WizardPanel {

    /** Creates new form Preprocessing
     * @param pdata
     */
    public Preprocessing(ProjectionData pdata) {
        this.pdata = pdata;
        initComponents();

        for (StemmerType st : StemmerType.getTypes()) {
            this.stemmerComboBox.addItem(st);
        }

        for (MatrixTransformationType mtt : MatrixTransformationType.getTypes()) {
            this.matrixtransfComboBox.addItem(mtt);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        wordListTypeButtonGroup = new javax.swing.ButtonGroup();
        preProcessingPanel = new javax.swing.JPanel();
        luhnLabel = new javax.swing.JLabel();
        gramsComboBox = new javax.swing.JComboBox();
        gramsLabel = new javax.swing.JLabel();
        luhnLowerTextField = new javax.swing.JTextField();
        analyzeButton = new javax.swing.JButton();
        luhnUpperLabel = new javax.swing.JLabel();
        luhnUpperTextField = new javax.swing.JTextField();
        stemmerComboBox = new javax.swing.JComboBox();
        matrixTypePanel = new javax.swing.JPanel();
        matrixtransfComboBox = new javax.swing.JComboBox();
        wordListTypePanel = new javax.swing.JPanel();
        stopwordRadioButton = new javax.swing.JRadioButton();
        startwordRadioButton = new javax.swing.JRadioButton();
        useWeightCheckBox = new javax.swing.JCheckBox();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Corpus Pre-processing"));
        setLayout(new java.awt.GridBagLayout());

        preProcessingPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Parameters"));
        preProcessingPanel.setLayout(new java.awt.GridBagLayout());

        luhnLabel.setText("Luhn's lower cut");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        preProcessingPanel.add(luhnLabel, gridBagConstraints);

        gramsComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        preProcessingPanel.add(gramsComboBox, gridBagConstraints);

        gramsLabel.setText("Number of grams");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        preProcessingPanel.add(gramsLabel, gridBagConstraints);

        luhnLowerTextField.setColumns(5);
        luhnLowerTextField.setText("10");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        preProcessingPanel.add(luhnLowerTextField, gridBagConstraints);

        analyzeButton.setText("Analyze");
        analyzeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analyzeButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        preProcessingPanel.add(analyzeButton, gridBagConstraints);

        luhnUpperLabel.setText("Luhn's upper cut");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        preProcessingPanel.add(luhnUpperLabel, gridBagConstraints);

        luhnUpperTextField.setColumns(5);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        preProcessingPanel.add(luhnUpperTextField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        preProcessingPanel.add(stemmerComboBox, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(preProcessingPanel, gridBagConstraints);

        matrixTypePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Matrix Transformation"));
        matrixTypePanel.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        matrixTypePanel.add(matrixtransfComboBox, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(matrixTypePanel, gridBagConstraints);

        wordListTypePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Word List Type"));
        wordListTypePanel.setLayout(new java.awt.GridBagLayout());

        wordListTypeButtonGroup.add(stopwordRadioButton);
        stopwordRadioButton.setSelected(true);
        stopwordRadioButton.setText("Stop Words");
        stopwordRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        stopwordRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        wordListTypePanel.add(stopwordRadioButton, gridBagConstraints);

        wordListTypeButtonGroup.add(startwordRadioButton);
        startwordRadioButton.setText("Start Words");
        startwordRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        startwordRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        wordListTypePanel.add(startwordRadioButton, gridBagConstraints);

        useWeightCheckBox.setText("Use weights");
        useWeightCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        useWeightCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        wordListTypePanel.add(useWeightCheckBox, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(wordListTypePanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    private void analyzeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analyzeButtonActionPerformed
        this.refreshData();
        ProjectionWizardView view = (ProjectionWizardView) this.getTopLevelAncestor();
        LuhnCutAnalizer.getInstance(view).display(this.pdata);
        this.luhnLowerTextField.setText(Integer.toString(this.pdata.getLunhLowerCut()));
        this.luhnUpperTextField.setText(Integer.toString(this.pdata.getLunhUpperCut()));
    }//GEN-LAST:event_analyzeButtonActionPerformed

    @Override
    public void refreshData() {
        this.pdata.setStemmer((StemmerType) this.stemmerComboBox.getSelectedItem());
        this.pdata.setUseStopword(this.stopwordRadioButton.isSelected());
        this.pdata.setUseWeight(this.useWeightCheckBox.isSelected());
        this.pdata.setMatrixTransformationType((MatrixTransformationType) this.matrixtransfComboBox.getSelectedItem());
        this.pdata.setNumberGrams(this.gramsComboBox.getSelectedIndex() + 1);

        if (this.luhnLowerTextField.getText().trim().length() > 0) {
            this.pdata.setLunhLowerCut(Integer.parseInt(this.luhnLowerTextField.getText()));
        } else {
            this.pdata.setLunhLowerCut(1);
        }

        if (this.luhnUpperTextField.getText().trim().length() > 0) {
            this.pdata.setLunhUpperCut(Integer.parseInt(this.luhnUpperTextField.getText()));
        } else {
            this.pdata.setLunhUpperCut(-1);
        }
    }

    private ProjectionData pdata;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton analyzeButton;
    private javax.swing.JComboBox gramsComboBox;
    private javax.swing.JLabel gramsLabel;
    private javax.swing.JLabel luhnLabel;
    private javax.swing.JTextField luhnLowerTextField;
    private javax.swing.JLabel luhnUpperLabel;
    private javax.swing.JTextField luhnUpperTextField;
    private javax.swing.JPanel matrixTypePanel;
    private javax.swing.JComboBox matrixtransfComboBox;
    private javax.swing.JPanel preProcessingPanel;
    private javax.swing.JRadioButton startwordRadioButton;
    private javax.swing.JComboBox stemmerComboBox;
    private javax.swing.JRadioButton stopwordRadioButton;
    private javax.swing.JCheckBox useWeightCheckBox;
    private javax.swing.ButtonGroup wordListTypeButtonGroup;
    private javax.swing.JPanel wordListTypePanel;
    // End of variables declaration//GEN-END:variables
}
